Assignment2_Morgenmadsbuffeten/Controllers/CheckedInGuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment2_Morgenmadsbuffeten.Data;
using Assignment2_Morgenmadsbuffeten.Models;
using Microsoft.AspNetCore.Authorization;

namespace Assignment2_Morgenmadsbuffeten.Controllers
{
    [Authorize("IsWaiter")]
    public class CheckedInGuestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CheckedInGuestController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CheckedInGuest
        [AllowAnonymous]
        public async Task<IActionResult> Index(DateTime date)
        {
            if(date.Year == 1)
            {
                date = DateTime.Today;
            }

            var checkedIn = (await _context.CheckedInGuests.ToListAsync()).Where(x => x.Date.Day == date.Day);
            return View(checkedIn); 
        }

        // GET: CheckedInGuest/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedInGuest = await _context.CheckedInGuests
                .FirstOrDefaultAsync(m => m.CheckedInGuestId == id);
            if (checkedInGuest == null)
            {
                return NotFound();
            }

            return View(checkedInGuest);
        }

        // GET: CheckedInGuest/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CheckedInGuest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CheckedInGuestId,Date,RoomNumber,Adults,Children")] CheckedInGuest checkedInGuest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkedInGuest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(checkedInGuest);
        }

        // GET: CheckedInGuest/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedInGuest = await _context.CheckedInGuests.FindAsync(id);
            if (checkedInGuest == null)
            {
                return NotFound();
            }
            return View(checkedInGuest);
        }

        // POST: CheckedInGuest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CheckedInGuestId,Date,RoomNumber,Adults,Children")] CheckedInGuest checkedInGuest)
        {
            if (id != checkedInGuest.CheckedInGuestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkedInGuest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckedInGuestExists(checkedInGuest.CheckedInGuestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(checkedInGuest);
        }

        // GET: CheckedInGuest/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedInGuest = await _context.CheckedInGuests
                .FirstOrDefaultAsync(m => m.CheckedInGuestId == id);
            if (checkedInGuest == null)
            {
                return NotFound();
            }

            return View(checkedInGuest);
        }

        // POST: CheckedInGuest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var checkedInGuest = await _context.CheckedInGuests.FindAsync(id);
            _context.CheckedInGuests.Remove(checkedInGuest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckedInGuestExists(long id)
        {
            return _context.CheckedInGuests.Any(e => e.CheckedInGuestId == id);
        }
    }
}

Assignment2_Morgenmadsbuffeten/Controllers/ExpectedGuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment2_Morgenmadsbuffeten.Data;
using Assignment2_Morgenmadsbuffeten.Models;
using Microsoft.AspNetCore.Authorization;

namespace Assignment2_Morgenmadsbuffeten.Controllers
{
    [Authorize("IsReceptionist")]
    public class ExpectedGuestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExpectedGuestController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ExpectedGuest
        public async Task<IActionResult> Index()
        {
            return View(await _context.ExpectedGuests.ToListAsync());
        }

        // GET: ExpectedGuest/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expectedGuest = await _context.ExpectedGuests
                .FirstOrDefaultAsync(m => m.ExpectedGuestId == id);
            if (expectedGuest == null)
            {
                return NotFound();
            }

            return View(expectedGuest);
        }

        // GET: ExpectedGuest/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ExpectedGuest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpectedGuestId,Date,RoomNumber,Adults,Children")] ExpectedGuest expectedGuest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(expectedGuest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expectedGuest);
        }

        // GET: ExpectedGuest/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expectedGuest = await _context.ExpectedGuests.FindAsync(id);
            if (expectedGuest == null)
            {
                return NotFound();
            }
            return View(expectedGuest);
        }

        // POST: ExpectedGuest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ExpectedGuestId,Date,RoomNumber,Adults,Children")] ExpectedGuest expectedGuest)
        {
            if (id != expectedGuest.ExpectedGuestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expectedGuest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpectedGuestExists(expectedGuest.ExpectedGuestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expectedGuest);
        }

        // GET: ExpectedGuest/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expectedGuest = await _context.ExpectedGuests
                .FirstOrDefaultAsync(m => m.ExpectedGuestId == id);
            if (expectedGuest == null)
            {
                return NotFound();
            }

            return View(expectedGuest);
        }

        // POST: ExpectedGuest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var expectedGuest = await _context.ExpectedGuests.FindAsync(id);
            _context.ExpectedGuests.Remove(expectedGuest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpectedGuestExists(long id)
        {
            return _context.ExpectedGuests.Any(e => e.ExpectedGuestId == id);
        }
    }
}

Assignment2_Morgenmadsbuffeten/Views/Shared/_Layout.cshtml
@{
    var IsReceptionist = false;
    if (User.HasClaim("Reception", "Yes"))
    {
        IsReceptionist = true;
    }
}

@{
    var IsWaiter = false;
    if (User.HasClaim("Restaurant", "Yes"))
    {
        IsWaiter = true;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment2_Morgenmadsbuffeten</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/thebreakfastbuffetmobile.css" media="only screen and (max-width: 480px)" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
              crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </environment>
    </head>
<body>
<div id="wrapper">
    <header>
        <h1>The Breakfast Buffet</h1>
    </header>
    <nav>
        <ul>
            <li><a href="/Home/Index">Home</a></li>
            <li><a href="/Home/Kitchen">Kitchen</a></li>
            <li><a asp-controller="ExpectedGuest" asp-action="Index">Reception</a></li>
            @if (IsReceptionist)
            {
                <li>
                    <a asp-controller="ExpectedGuest" asp-action="Create">Add guests</a>
                </li>
                <li>
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit">Logout</button>
                    </form>
                </li>
            }
            <li><a asp-controller="CheckedInGuest" asp-action="Create">Restaurant</a></li>
            @if (IsWaiter)
            {
                <li>
                    <a asp-controller="CheckedInGuest" asp-action="Index">Checked-In guests</a>
                </li>
                <li>
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit">Logout</button>
                    </form>
                </li>
            }
        </ul>
    </nav>
    <div>
        <main id="content">
            @RenderBody()
        </main>
        <div id="footer">
            <small>
                <i>
                    Copyright &copy; 2020 The Breakfast Buffet<br/>
                    <a href="mailto:TheBreakfastBuffet@live.com">TheBreakfastBuffet@live.com</a>
                </i>
            </small>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>